CREATE VIEW vwEquipmentCostPerYear AS
SELECT 
	TRIM(EQPTCODE) AS EQPTCODE,
	YR AS YEAR,
	SUM(DEPRECIATN) AS Depreciation,
	SUM(INSURANCE) AS Insurance,
	SUM(REGFEES) AS RegFees,
	SUM(FUEL) AS Fuel,
	SUM(LUBRICANTS) AS Lubes,
	SUM(LABOUR) AS Labour,
	SUM(SPAREPARTS) AS SpareParts,
	SUM(REPAIR) AS Repair3rdP,
	SUM(CONSINDIR) AS ConsIndir,
	SUM(CONSDIRECT) AS ConsDirect,
	SUM(TYRESTUBES) AS TyresTubes,
	SUM(MATERIALS) AS Materials,
	SUM(DRYDOC) AS DryDock,
	SUM(LABOUR) + SUM(SPAREPARTS) + 
		SUM(REPAIR) + SUM(CONSINDIR) + 
		SUM(CONSDIRECT) + SUM(TYRESTUBES) + 
		SUM(MATERIALS) + SUM(DRYDOC) AS TotalCost,
	CONCAT(TRIM(EQPTCODE),YR) AS id
FROM
	dbo.tblMC3
GROUP BY TRIM(EQPTCODE), YR
ORDER BY TRIM(EQPTCODE), YR
OFFSET 0 ROWS

